nginx:
  # Note : Only nginx:alpine supports bcrypt.
  # If you don't need to use bcrypt, you can use a different tag.
  # Ref. https://github.com/nginxinc/docker-nginx/issues/29
  image: "nginx:alpine"
  ports:
    - 5044:8443
  restart: always
  links:
    - registry:registry
  volumes:
    - /home/admin/registry/:/etc/nginx/
    #- /home/admin/auth/nginx.conf:/etc/nginx/nginx.conf:ro
registry:
  image: registry:2
  ports:
    - 5000:5000
  restart: always
  volumes:
    - /data/registry:/var/lib/registry

